hw1 completed + gradle
Furetur/KotlinProgramming2 pull request #1
Opened 2020-09-12 17:30 UTC by Furetur

2020-09-14 08:48 UTC, SpirinEgor requested changes
А как гарантируется работоспособность тестов?
Вот ты пишешь, что за 100 шагов будут все компьютеры заражены. При этом вероятность заражения от 0 до 1, то есть вполне возможна ситуация, когда на всех 100 шагах компьютер не заразился.

2020-09-14 08:51 UTC, Furetur commented
Насколько я помню я создаю сети из Виндоус компов, у которых вероятность заражения 100%

2020-09-14 08:51 UTC, Furetur commented
Чтобы все детерминирвованно работало

2020-09-14 08:58 UTC, SpirinEgor commented
Понял, но тогда проблема в тестировании случаев, когда вероятность не 1 (такие случаи вообще не тестируются). Почему при вероятности в 0.5 всё также будет работать, вдруг в программе ошибка и всё равно все компьютеры заразятся?

2020-09-14 09:00 UTC, Furetur commented
А как такое тестить, убрать элемент рандома и самому в тесте генерировать случайное (неслучайное) число?

2020-09-14 14:43 UTC, SpirinEgor commented
Да, мыслишь верно

2020-09-17 18:21 UTC, SpirinEgor approved these changes

2020-09-21 15:11 UTC, merged