244. Порсев 3.1
Furetur/KotlinProgramming2 pull request #6
Opened 2020-09-30 15:32 UTC by Furetur

2020-09-30 18:48 UTC, SpirinEgor requested changes
Прямо очень сильный переизбыток сущностей. Кажется, что большая часть просто бесполезна. На сервер по сути нужно 2 объекта: один слушает события, обрабатывает их, а второй уже контролирует есть ли свободные безопасным способом

2020-09-30 18:48 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw3/Car.kt
> +    val departure = if (departureTime != null) Timeline.CarEvent(Timeline.CarEventType.DEPARTURE, this) else null
Ты же на Котлине пишешь, тут столько всего для работы с null
```
departureTime.?let {...}
```

2020-09-30 18:48 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw3/ParkingSimulation.kt
> +    private fun runTimeframe(timeframe: Timeline.Timeframe) = runBlocking {
Кажется, что это у Timeframe должна быть функция run, которая уже выполняет всю логику по его обработке

2020-09-30 18:48 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw3/ParkingSimulation.kt
> +    private fun logTimeframeStart(frame: Timeline.Timeframe) {
А для логирования сам фрейм похоже не нужен, важнее указать какое время сейчас. То есть просто время тут использовать

2020-09-30 18:48 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw3/Timeline.kt
> +data class Timeline(val cars: List<Car>) {
Хмм, ну data class, как ни странно, для хранения каких-то данных и всё. А у тебя внутри ещё парочка классов, немного логики инициализации... Ну и какую-то логику из симуляции сюда можно перенести

2020-09-30 18:48 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw3/server/ParkingSystem.kt
> +    private val emptySpaces = Stack<Int>()
А зачем стек из интов? Кажется, что можно и просто число поддерживать

2020-09-30 18:48 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw3/server/ParkingSystem.kt
> +class ParkingSystem(private val parkingSpacesCount: Int) : EventsHandler {
Кажется, что тут нет никакой защиты от коллизии и других возможных проблем, если запросы будут приходить очень быстр

2020-09-30 18:48 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw3/server/ParkingSystem.kt
> +class ParkingSystem(private val parkingSpacesCount: Int) : EventsHandler {
А, ну возможно я запутался...

2020-09-30 18:48 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw3/server/ParkingSystem.kt
> +class ParkingSystem(private val parkingSpacesCount: Int) : EventsHandler {
Но вроде всё равно одного числа для хранения будет достаточно

2020-10-02 17:01 UTC, SpirinEgor requested changes

2020-10-02 17:01 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw3/simulation/ParkingSimulation.kt
> +    }
Если я правильно, то у тебя корутина создаётся на автомате. Почему при этом не возникает конфликтов на сервере непонятно.
Более того, непонятно, а зачем делать корутины на автомате, там логика простая -- запрос на сервер, ждём результат, сообщаем машине. Вся логика по получению запросов, созданию корутин, обращение к систему должны быть на сервере.

2020-10-02 17:07 UTC, Furetur commented on src/main/kotlin/homeworks/hw3/simulation/ParkingSimulation.kt
> +    }
Конфликтов, связанных с многопоточностью, не возникает, потому что `ParkingServer.kt` делает thread confinement и обрабатывает все запросы в 1 потоке

2020-10-02 17:10 UTC, Furetur commented on src/main/kotlin/homeworks/hw3/simulation/ParkingSimulation.kt
> +    }
Автомат в любом случае же должен создавать корутину, потому что делает асинхронный запрос данных

2020-10-02 17:13 UTC, Furetur commented on src/main/kotlin/homeworks/hw3/simulation/ParkingSimulation.kt
> +    }
В этом методе, я просто делаю так, чтобы несколько машин параллельно пользовались автоматами в этой симуляции. Для этого мне точно надо запускать корутину и параллелить запросы машин

2020-10-02 17:16 UTC, Furetur commented on src/main/kotlin/homeworks/hw3/simulation/ParkingSimulation.kt
> +    }
Можно конечно написать какой-нибудь объект, который симулирует передачу данных, чтобы его мог прослушивать сервер, а в него отправлять данные могли клиенты

2020-10-05 12:48 UTC, SpirinEgor commented on src/main/kotlin/homeworks/hw3/simulation/ParkingSimulation.kt
> +    }
Ну у тебя подъехала машина к автомату, постучалась в него, ждёт результата и куда-то едет. Кажется, что если бы автомат обрабатывал много машин, то асинхронность имела бы смысл. Но у нас такого нет, так что корутина не нужна (если очень хочешь, то можешь оставить).
Меня больше беспокоит, что корутина создаётся в одном месте, идёт запрос, а на сервере то всё приходит в одно место. Поэтому на сервере образуется очередь из запросов. Обрабатывать запросы в 1 потоке можно, но ты ровном месте увеличил время ответа на запросы (представь час-пик, запросов идёт очень много).


Симулировать передачу данных надо в том плане, что есть сущность для отправки и получения сообщений (одна на автомате, другая на сервере). На самом деле одна просто дёргает метод другой.

2020-10-14 09:51 UTC, SpirinEgor approved these changes

2020-10-14 09:53 UTC, merged